version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      # Spring Boot 설정
      PORT: ${PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # DB (왼쪽은 prod.yml 변수명 : 오른쪽은 .env 변수명)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USER: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # 저장소 및 AWS 설정
      STORAGE_TYPE: ${STORAGE_TYPE}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}
    ports:
      - "8081:${PORT}"
    volumes:
      - ./BinaryContentStorage:/var/lib/discodeit/storage