server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: http://localhost:9090

logging:
  level:
    root: DEBUG
    com.zaxxer.hikari: INFO
    javax.management: INFO
    sun.rmi: INFO

info:
  major-config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: "LOCAL"
      path: "${user.dir}/storage"
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
